[package]
name = "floc_blog"
version = "0.1.0"
authors = ["ForLoveOfCats <floc@unpromptedtirade.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
pulldown-cmark = "0.8.0"
